(ns carve.core-test
  (:require
   [carve.core :as core]
   [clojure.java.io :as io]
   [clojure.test :as t :refer [deftest is]]))

(deftest run!-test
  (let [uberscript (.getPath (io/file "test-resources" "uberscript" "uberscript.clj"))
        expected '[{:filename "test-resources/uberscript/uberscript.clj",
                    :row      6,
                    :col      1,
                    :ns       medley.core,
                    :name     find-first}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      20,
                    :col      1,
                    :ns       medley.core,
                    :name     dissoc-in}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      38,
                    :col      1,
                    :ns       medley.core,
                    :name     assoc-some}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      47,
                    :col      1,
                    :ns       medley.core,
                    :name     update-existing}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      63,
                    :col      1,
                    :ns       medley.core,
                    :name     update-existing-in}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      88,
                    :col      1,
                    :ns       medley.core,
                    :name     map-entry}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      95,
                    :col      1,
                    :ns       medley.core,
                    :name     map-kv}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      102,
                    :col      1,
                    :ns       medley.core,
                    :name     map-keys}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      107,
                    :col      1,
                    :ns       medley.core,
                    :name     map-vals}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      123,
                    :col      1,
                    :ns       medley.core,
                    :name     map-kv-keys}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      130,
                    :col      1,
                    :ns       medley.core,
                    :name     map-kv-vals}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      155,
                    :col      1,
                    :ns       medley.core,
                    :name     remove-kv}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      161,
                    :col      1,
                    :ns       medley.core,
                    :name     remove-keys}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      167,
                    :col      1,
                    :ns       medley.core,
                    :name     remove-vals}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      173,
                    :col      1,
                    :ns       medley.core,
                    :name     queue}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      180,
                    :col      1,
                    :ns       medley.core,
                    :name     queue?}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      187,
                    :col      1,
                    :ns       medley.core,
                    :name     boolean?}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      194,
                    :col      1,
                    :ns       medley.core,
                    :name     least}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      202,
                    :col      1,
                    :ns       medley.core,
                    :name     greatest}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      210,
                    :col      1,
                    :ns       medley.core,
                    :name     join}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      218,
                    :col      1,
                    :ns       medley.core,
                    :name     deep-merge}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      233,
                    :col      1,
                    :ns       medley.core,
                    :name     mapply}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      252,
                    :col      1,
                    :ns       medley.core,
                    :name     interleave-all}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      271,
                    :col      1,
                    :ns       medley.core,
                    :name     distinct-by}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      298,
                    :col      1,
                    :ns       medley.core,
                    :name     dedupe-by}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      317,
                    :col      1,
                    :ns       medley.core,
                    :name     take-upto}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      336,
                    :col      1,
                    :ns       medley.core,
                    :name     drop-upto}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      352,
                    :col      1,
                    :ns       medley.core,
                    :name     indexed}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      366,
                    :col      1,
                    :ns       medley.core,
                    :name     insert-nth}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      391,
                    :col      1,
                    :ns       medley.core,
                    :name     remove-nth}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      412,
                    :col      1,
                    :ns       medley.core,
                    :name     replace-nth}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      433,
                    :col      1,
                    :ns       medley.core,
                    :name     abs}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      460,
                    :col      1,
                    :ns       medley.core,
                    :name     deref-reset!}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      466,
                    :col      1,
                    :ns       medley.core,
                    :name     ex-message}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      475,
                    :col      1,
                    :ns       medley.core,
                    :name     ex-cause}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      484,
                    :col      1,
                    :ns       medley.core,
                    :name     uuid?}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      489,
                    :col      1,
                    :ns       medley.core,
                    :name     uuid}
                   {:filename "test-resources/uberscript/uberscript.clj",
                    :row      497,
                    :col      1,
                    :ns       medley.core,
                    :name     random-uuid}]]
    (is (= expected
           (core/run! {:paths [uberscript]}))
        "Returns (by default) lint data as a vanilla data structure")
    (is (= ""
           (with-out-str (core/run! {:paths [uberscript]})))
        "Prints nothing during operation")))
